name: somafm
grade: stable
adopt-info: somafm
license: GPL-3.0+

base: core20
confinement: strict

apps:
  somafm:
    command: usr/bin/com.github.alexkdeveloper.somafm
    extensions: [gnome-3-38]
    plugs:
      - pulseaudio
      - network
    slots:
      - dbus-daemon
    common-id: com.github.alexkdeveloper.somafm

parts:
  somafm:
    plugin: meson
    source: https://github.com/alexkdeveloper/somafm.git
    source-branch: main
    meson-parameters: [--prefix=/snap/somafm/current/usr]
    build-packages:
      - libgstreamer1.0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - gettext
    organize:
      snap/somafm/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.alexkdeveloper.somafm.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.alexkdeveloper.somafm
